spring.application.name=MyBudget
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
server.port=${PORT:8080}

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3307/hogarbudget}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:root}

logging.level.org.springframework=INFO
logging.level.org.hibernate=INFO
logging.level.HogarBudget=INFO
logging.level.root=INFO

# Activar Flyway expl�citamente
spring.flyway.enabled=true

# Ubicaci�n por defecto donde Spring Boot busca las migraciones
spring.flyway.locations=classpath:db/migration

# Mostrar logs detallados de Flyway
logging.level.org.flywaydb=DEBUG

# JWT Configuration
jwt.secret=${JWT_SECRET:MyBudgetSecretKey2024SuperSeguraQueTemMaisDe256BitsParaHMAC}
jwt.expiration=${JWT_EXPIRATION:86400000}