spring.application.name=MyBudget
spring.datasource.url=jdbc:mysql://127.0.0.1:3307/hogarbudget
spring.datasource.username=root
spring.datasource.password=123456
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
debug=true


logging.level.org.springframework=DEBUG
logging.level.org.hibernate=DEBUG
logging.level.HogarBudget=DEBUG
logging.level.root=DEBUG

# Activar Flyway explícitamente
spring.flyway.enabled=true

# Ubicación por defecto donde Spring Boot busca las migraciones
spring.flyway.locations=classpath:db/migration

# Mostrar logs detallados de Flyway
logging.level.org.flywaydb=DEBUG