spring.application.name=MyBudget
spring.datasource.url=jdbc:mysql://${MYSQLHOST}:${MYSQLPORT}/${MYSQL_DATABASE}
spring.datasource.username=${MYSQLUSER}
spring.datasource.password=${MYSQLPASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
server.port=${PORT:8080}

logging.level.org.springframework=INFO
logging.level.org.hibernate=INFO
logging.level.HogarBudget=INFO
logging.level.root=INFO

# Activar Flyway expl�citamente
spring.flyway.enabled=true

# Ubicaci�n por defecto donde Spring Boot busca las migraciones
spring.flyway.locations=classpath:db/migration

# Mostrar logs detallados de Flyway
logging.level.org.flywaydb=DEBUG